name: Build and Push 42sh to GHCR

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker image tag
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          TAG=${GITHUB_REF#refs/tags/}
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Prepare for build
        run: ./scripts/build/1-prepare-docker.sh

      - name: Build image with version tag
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: Tag image as latest
        run: docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      - name: Push version tag
        run: docker push $IMAGE_NAME:$TAG

      - name: Push latest tag
        run: docker push $IMAGE_NAME:latest
